### ISSUE TITLE
Information for those wanting to use without a Database

### ISSUE THREAD

**Issue by whithajess** [softace/activerecord-tableless#25]
I think it may pay to include details about using this gem without a database.

Doing a rails install without Active Record - `rails new example --skip-active-record`

In `config/application.rb`

```
require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
# require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"
require "rails/test_unit/railtie"
```

Active Record is not required by bundler (because 'activerecord' is the gem and 'active_record' is the lib) it is normally done by the `require 'active_record/railtie'` (presumably by design) so to get activerecord-tableless working without a database you will need to `require 'active_record'` in `config/application.rb`

**Comment by ypan887** [comment]
I got this error when trying to  require 'active_record' in config/application.rb , any idea what the problem maybe? Thanks

Failure/Error: raise ConnectionNotEstablished, "No connection pool for #{klass}" unless pool

      ActiveRecord::ConnectionNotEstablished:
        No connection pool for ActiveRecord::Base

**Comment by pboling** [comment]
@ypan887 even if you are not using a database ActiveRecord still expects to find a `config/database.yml` with connection settings.  That is the crux of the problem, but, obviously you don't have a database so not sure what you would put in there.

I have only ever used activerecord-tableless in a scenario where I did have a database, and I just wanted to have some models that did not have tables.

**Comment by ypan887** [comment]
@pboling Thanks for the response. I am looking for a way to implement the model association so that I could generate Json output with nested attributes in my form, and I don't needed to have any database because the database is in the server side. So my temporary solution is to just have a sqlite3 gem and database.yml in my project, except I never need to do rake db:create to actually create the database. I don't like to have something in my project that has no practical usage , but I couldn't find any other solution for now.

**Comment by pboling** [comment]
For future googlers: I have created two gems that provide some/all of the functionality of this gem:
• [activerecord-tablefree](https://rubygems.org/gems/activerecord-tablefree) is a fork of this gem which is Rails 5+ (only) compatible.
• [anonymous_active_record](https://rubygems.org/gems/anonymous_active_record) is a way to create anonymous ActiveRecord classes for use with a test suite.
